server:
  port: ${PORT:8092}
  servlet:
    context-path: /pis


spring:
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/app_db}
    username: ${DATASOURCE_USER:user}
    password: ${DATASOURCE_PASS:password}