package be.kdg.prog6.common.events;

public enum EventCatalog {

    TICKET_CREATED,

    TICKET_CHECKED_IN_OUT,
    ATTRACTION_ACTIVITY_CREATED,
    ATTRACTION_CREATED,

    REFRESHMENT_STAND_ACTIVITY_CREATED,
}
