POST http://localhost:8094/visitor
Content-Type: application/json

{
  "name": "Bobby",
  "address": "123 Main St",
  "email": "helslo@gmsail.com",
  "dateOfBirth": "1990-01-01"
}

###

POST http://localhost:8094/visitor/b8d3d33e-bcf9-46b5-b588-053d0551c71f/ticket
Content-Type: application/json

{
  "ticketDurationType": "DAY",
  "ticketAgeType": "ADULT",
  "validFrom": "2023-11-01T12:00:00",
  "validUntil": "2023-12-01T14:00:00"
}


###

GET http://localhost:8093/queGate/675a606b-8ba0-4462-a75a-e438fa221a01
###

POST http://localhost:8093/queGate/checkIn
Content-Type: application/json

{
  "ticketUUID": "e698d84f-5d4d-4450-87df-89cadd31d343",
  "queGateUUID": "64dc2a96-a567-4b2f-854d-8c5a2bf1cca6",
  "ticketAction": "CHECK_IN"
}
###

POST http://localhost:8093/queGate/checkOut
Content-Type: application/json

{
  "ticketUUID": "e698d84f-5d4d-4450-87df-89cadd31d343",
  "queGateUUID": "64dc2a96-a567-4b2f-854d-8c5a2bf1cca6",
  "ticketAction": "CHECK_OUT"
}



