POST http://localhost:8094/visitor
Content-Type: application/json

{
  "name": "Bobby",
  "address": "123 Main St",
  "email": "helslo@gmsail.com",
  "dateOfBirth": "1990-01-01"
}

###

POST http://localhost:8094/visitor/b8d3d33e-bcf9-46b5-b588-053d0551c71f/ticket
Content-Type: application/json

{
  "ticketDurationType": "DAY",
  "ticketAgeType": "ADULT",
  "validFrom": "2023-11-01T12:00:00",
  "validUntil": "2023-12-01T14:00:00"
}


###

GET http://localhost:8093/queGate/27eabf78-73a9-49b5-b33f-e7517047cecd
###

POST http://localhost:8093/queGate/checkIn
Content-Type: application/json

{
  "ticketUUID": "085375d0-8b31-44af-beae-04282d6dd150",
  "queGateUUID": "f63bb81b-321b-4e0a-9003-4e2abeebea1e",
  "ticketAction": "CHECK_IN"
}
###

POST http://localhost:8093/queGate/checkOut
Content-Type: application/json

{
  "ticketUUID": "93f157da-a820-491a-98dc-3cad3f851bac",
  "queGateUUID": "27eabf78-73a9-49b5-b33f-e7517047cecd",
  "ticketAction": "CHECK_OUT"
}

###

GET http://localhost:8092/interactiveMap


